### ISSUE TITLE
Failed to decompress downloaded paste

### ISSUE THREAD

**Issue by bambi73** [r4sas/PBinCLI#14]
I tried to download paste (I'm not author) https://priv.atebin.com/?fb0daaba7acd7f6c#HrgT6DPj4BH7O1FrGS3jPrpeWMRAeIe0MQw4TSm9tvE=
but it failed to decompress received content with

```
$ pbincli get fb0daaba7acd7f6c#HrgT6DPj4BH7O1FrGS3jPrpeWMRAeIe0MQw4TSm9tvE=
Paste received!
Traceback (most recent call last):
  File "G:\Development\python\a\venv\Scripts\pbincli-script.py", line 11, in <module>
    load_entry_point('PBinCLI==0.2b1', 'console_scripts', 'pbincli')()
  File "G:\Development\python\a\venv\lib\site-packages\pbincli-0.2b1-py3.6.egg\pbincli\cli.py", line 77, in main
  File "G:\Development\python\a\venv\lib\site-packages\pbincli-0.2b1-py3.6.egg\pbincli\actions.py", line 111, in get
  File "G:\Development\python\a\venv\lib\site-packages\pbincli-0.2b1-py3.6.egg\pbincli\format.py", line 200, in decrypt
  File "G:\Development\python\a\venv\lib\site-packages\pbincli-0.2b1-py3.6.egg\pbincli\format.py", line 144, in __decompress
ValueError: byte must be in range(0, 256)
```

You can check link above that paste exist, isn't password protected and web site itself has no problems to process it.

I added some logging to see what's input for decompressing (output of decryption):

```
Paste received!
Decrypted text: b'77+M776977+J776WI++/p+++mTbvvrbvv6/vvqvvvojvvpLvvo/vv7/vvrTvv5vvvqhs776OYu++kS3vvqlOcU7vvpnvvqTvv5TvvqpS776X77+177+Lfe+/ugTvvoAPQDADEVAMCe++ggsdLe++vO+/t0YLb3Tvvrzvv7PvvrJ777+h776N776v776HN2Bf776C77+f77+nHe++vikCQO++ku+/jV/vvq1W776T776s77+KBCLvvr7vv6Ed776fd++/uu+/me++unoo77+2ZXfvvr9u776P77+N77+Pf++/su+/pk/vvopVXe+/tu+/ve+/j39SNe++h3F4776677+t77+a77+xUAzvv67vvpvvv6Hvv6nvv5djP1TvvptT776xcu+/je+/oO++uu++p++/i+++ul3vv50X776r7762fu++ul8/77+9776p77+9776h77+dbHo3PH3vv7sn776/77+477+Z7765Bx9dXe+/k+++r+++l++/ozDvvrRNMe++nA7vv67vv6c/776R776/77+4776PLO++h+++pu++oH/vvp4e7766776K776e776Q776+77+yJ++/he++uhzvv4rvvqdD776777+d77+W77+0TXpvXR56Zz8u7767776tG37vv77vvpPvv79uaFc/77+577+FK++/vlDvvrHvv5rvvpUH77+6flFX77+977+w776zf+++kHfvv43vvqzvvq9a77+/77+8J++/uO++mu++re+/gj/vv7oXf++/t++/t++/he+/j++/imLvv5fvvrkNPe+/ue+/s27vv7vvv6rvvqcf77+/77+677+rdz7vv7zvv7zvvr1f776977+5ae+/t++/me+/i+++t+++v++/vnV3cO++r+++v++/vO+/jQt377+n77+e77+477+y776f776O77+v7768eu++uX9/eO+/uO+/pO+/p++/v0Vf77+977+077+Z776z7763f+++ontdV++/ve++qu+/re+/lu+/v3oo77+777+BPX3vv7fvvq3vvrfvvp/vvr3vv7/vv6Y7b+++ve+/u++/rO+/me+/u++/rzx777+n77+ZG2/vv77vv6tq776177+9V++/uu+/vO+/k2bvv4RBfe++pO++i+++p+++n3xQ776877+a7765Yu+/m+++tu+/q+++ou++re+/l++/he+/kO++le+/q2rvvqjvv5rvvqbvvr/vvr3vvr0t77+K776Gfu++snNNURbvv73vv5jvv5Hvv4nvv7Xvvq4o776H776hXO+/ne+/v++/rB/vv4ofZQfvv6/vv4zvv68A776rfu+/s+++p2/vvr3vv7/vv74b77+v776977+177+m776777+v776/77+377+O77677766776DdyY7eO+/p+++g++/ou++i3J9Kn7vv5Xvv5DvvqrvvrHvv6hjRUvvv67vv5zvv7rvv4da77+i7767776277+ETe+/m+++je+/u+++p++/r+++vO+/se+/jhs/77+V77+V7768O1nvv43vvrty776e776177+bDO++hTvvvrnvvqLvv53vv6AAC+++ou+/su+/le+/ve++vmx+776sNe+/vXTvv77vv5jvv55/77+j77+Z776b77+v776+77+377+s776nb+++v++/v++/tu++s+++t++/nn3vv6vvv5kb776677+O776f77+SV++/nu++i+++l++/ue+/kw/vvorvv4/vv5wwVO+/je++lu++ru+/tlBWHRZK77+r77+t77+l77+K7767776y77+pae++t3vvv7rvv73vvpMfa++/ie+/r++/vQfvvpfvv7zvv54H77+F77+L77+d7764K+++m++/re++ojjvvrUjOG
........... (only part)
```

It's Base64 but it looks extremely fishy.

I cloned this paste (https://priv.atebin.com/?66dfee161d6babc7#F+0Fxa4qBzAAf20PgrbuDAI9xnO71JKcUuh/E+JRhTU=) and I'm able to download it just fine. Log output looks quite different too:

```
Paste received!
Decrypted text: b'w4xcw4nCkhxHcsK9w7MrwoLCkMOZw4BswqzCusOZG8KAbg4IGEASRHMIwpJiwrcEwo0WG8KLw4rCjMKqCnRuw4zCpcKKw4XDkxx0w5dlwq7Dug99D39Awr/CoMO3w5wjMsKzwpZuYMOIwpZMNgRRw4wlw4LDg8ODw73DuXPDt8OIecKaw7rCpcOJbX3Ck8KWwqvDosKzB8OHD0zCksOZwqbDucOswoEvwqrCrj3CmMOXZVfCmcOWw73DlB7CvMOrwprDlsOPw5YmcUXDq8OqwoNpViY3JinCs8KDPD14HH/ClMKzWcOjw5rCg8OTB8OPwp7DnjbDsMOKZRluT8K7wrYtC8OTwq4rw7fDmQPDvcKPw77CkWlbGMO8OcKoasKPETbCp3xgUsObw5rCg8K2wpzDjzPCvMKJeTNbNS5ewrbDtcOcwrXCnz3DuMK7wrZMHjzCu8KWwodMwrLCsBXDnjfCmW/DmsKnwp/DqFx7w6TDs8OpZw/DuFrClMKiH8O6w5lHwr83T8KtWcOUbsKGwpFfw5fDs8Orw4dffMO/w67DrMOlw6snw58dwr/CqsK/wro6fcO3fV3CucK3b354w6Euw53DkcKbwr9fwp1dX8OlF8Otw7LDi8OPfhfCpj44Pz99EMOWwprDuiYpw6vDtMOPwpVtWnfDsMOow6TDtMO8w6LDuMOsw6TDkcO5w7nDhcOZw7nDmcO5w5HDscKfwpNkw75nPH9QdFTDlMOnQXhcw7nDlFwvwpzCmcKXZWrDiiw1bW1Tw5/DusKyaA4PD8KNLXBlw6EKY03Dk8OVw5Bcw6PCjG1bwpvDnDzDvcOEw57DiwrDjsO2wq/CgFIfPz7CucK4OHpycsO8w6jDosOJw5nCo8KwwoLCs8KdFcKcfWrCvsKxw6nDmnxXQGoKwr3DshDCuXbDqX3CicO4KMKKOCvDqy4/ODs6O3ocwqR5wrQjw40jw5Vnw6Zmwq1xa2fDihkVaGDDpcOJTW7Ci8O7wpLDqcOxfsK1XRzCnR8/enLDvsO4w7TDosO0w7zDpMORw4nDuVHCkMOzMV55MhbDs8OxwqfDpivDl8K2wr7CmGNrK8OrawoKeRvDncOyw5oWDVbCm8Ojw77Dh8O3JcOywpPDnyjDssKTT8ONw5XColvDmGI+McOrwrLCo8Onw40XLcOlXsO6wrrDrcKcacK7wrpwwqnDsUVbYlFzX2fDtyXDusO5wpYFHMKfwp1GMcOPdyzDoMO8U8OzwqprYMKLEzPCk8K/w69NwoMXwrtiRMOHwr7DmBHDowJiWMOoQsK2GHvCusKyN8O8w5lVw5FFw5Quwrs8w4fDo0vCm1g6wr3CmTp5PsKrHV3CqlzCusO6wr7CpMK/OMOawpLDvsOkw7gsKMOxw6JoW8O6wovCo8ORZl/CmhXCoMOaNMKLwrLCqijCnQjCj8K1AcODwr8owovDuQwPwpkrw7/Ck8Ksclp2NArCvMKYTsOtwrwxwpjDixzCm8OcZxlXw7fDg8KbwpfDt8K2wpzDo8Otw6U8OQ4YdXHCvMKzwpxjbAYiVMK5Ml/DmBIBAxhRw7vDhMKZH1xywpPCucKmwpn
........... (only part)
```

This looks much more like proper Base64 string. And because it's clone then these outputs should be same (only guessing). Because clone is working fine then this issue is probably neither content or server (1.2.1) related.

Tried to download some another pastes from same source/author (even from different server) and results are again bad (same exception). Tried to create and download my own pastes and it works fine.

From that I'm guessing that pastes produced by this source/author are somehow incompatible with your decryption method.

**Comment by r4sas** [comment]
Looks like they used customized privatebin.js.
1.2.1 release hash: https://github.com/PrivateBin/PrivateBin/blob/1.2.1/tpl/bootstrap.php#L78
```		<script type="text/javascript" data-cfasync="false" src="js/privatebin.js?<?php echo rawurlencode($VERSION); ?>" integrity="sha512-5xT6WHyurvC0LFESbkycBMAjhsi0KL/Xhx2oU+d0bqiJPkWK6ZAZgZ7I02oQiXaLtFSLf7UqpBo5XEePlfhH7Q==" crossorigin="anonymous"></script>```
That service hash:
```		<script type="text/javascript" data-cfasync="false" src="js/privatebin.js?1.2.1" integrity="sha512-tRRKkyV2RYlU1b/PdUmLigAV8mAQpklblVO071AcQs5QbeUwBnK2L5zjbscm2+B2eRJ06luEisXuPowvFHN6fA==" crossorigin="anonymous"></script>```

**Comment by bambi73** [comment]
Looks like that's case for https://priv.atebin.com/.
But https://paste.fizi.ca/ has same hash as in PrivateBin repo and paste (from same author) https://paste.fizi.ca/?3820e060fe1ad01d#+nLw3tRTXAsuUF5jn7zmloOCtuYWNIjBqowhaK15ymo= shows same problems.

**Comment by r4sas** [comment]
Okay, I will check this tomorrow.

**Comment by r4sas** [comment]
Paste created via website
```
        'mode': 'gcm',
        'adata': '',
        'salt': '...',
        'ks': 256,
        'iter': 10000,
        'ct': '...',
        'ts': 128,
        'v': 1,
        'iv': '...',
        'cipher': 'aes'
```

Paste from author:
```
        'cipher': 'aes',
        'adata': '',
        'iv': '...',
        'ks': 128,
        'salt': '...',
        'ts': 128,
        'iter': 1000,
        'v': 1,
        'ct': '...',
        'mode': 'gcm'
```

In that case I can say that author of that pastes used some client with non-standart encryption configuration in `ks` and `iter` (order doesn't make sense). Will check what I can to do with it in SJCL.

**Comment by bambi73** [comment]
Thanks.

Btw I noticed difference between meta-data returned by server for working paste (some random public paste) https://paste.fizi.ca/?6b8f0f398aeacf7e#TZ9oUgYV/OOB4aFpGzjPMwdhjNBFdk2TD1N6RyQsMVY= and not working https://paste.fizi.ca/?3820e060fe1ad01d#+nLw3tRTXAsuUF5jn7zmloOCtuYWNIjBqowhaK15ymo=.

```
working: {'iv': 'bj7l4XD/fLUnBPWcq6ynPw==', 'v': 1, 'iter': 10000, 'ks': 256, 'ts': 128, 'mode': 'gcm', 'adata': '', 'cipher': 'aes', 'salt': 'g8leFC2UeQM=', 'ct': ... }
not working: {'iv': 'RqxyF2PWh5uXOIBC82dz+Q==', 'v': 1, 'iter': 1000, 'ks': 128, 'ts': 128, 'mode': 'gcm', 'adata': '', 'cipher': 'aes', 'salt': 'X/QnENC9+O0=', 'ct': ... }
```
Maybe that will help. 
But please note that I have no idea what these fields mean, only that they are used for setting up encryption key :).

**Comment by bambi73** [comment]
Heh, you was faster.

**Comment by r4sas** [comment]
Seems like SJCL works correctly...
![image](https://user-images.githubusercontent.com/7023612/59984009-372f0080-962e-11e9-96be-2ad5da0d147f.png)

**Comment by r4sas** [comment]
Please try again with latest commit.

**Comment by bambi73** [comment]
Works fine now. Thanks for your effort.
