### ISSUE TITLE
self signed certificate -  verification failed

### ISSUE THREAD

**Issue by muralikodali** [r4sas/PBinCLI#15]
pbincli throwing below error with self signed certificate

ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

**Comment by smsimeonov** [comment]
Just put `verify=<path/to/your/cert>` as a parameter to every request in api.py
Or if you have trouble with that, just replace your path with False, so the parameter to put becomes `verify=False`

Playing with certificates in Python can be a pain, especially when working with third party code.

**Comment by r4sas** [comment]
I'll add option to disable certificate verifying.

**Comment by muralikodali** [comment]
I  have installed letsencrypt certificate and tested again. It produced the following response:
**ERROR: Unable parse response as json. Received (size = 0):**

**Comment by r4sas** [comment]
Can you give link to your instance to check?
Also please check your PHP logs.

**Comment by muralikodali** [comment]
It is not 24x7 server.
please check the below given link.
`<removed>`

**Comment by r4sas** [comment]
```
# PRIVATEBIN_SERVER="https://<yourdomain>/privatebin/" pbincli send -d -t "TESTING FROM CLI"
Set paste version to 2
Passphrase:     BpGGeG29Hmn1VU7iASrmLGLcBx9Wvb2Rnv4dGpDZ2JiF
Request:        {"adata":[["1aOxmqTKc9lva5cXoeYK7Q==","EC6IBTy/0oY=",100000,256,128,"aes","gcm","zlib"],"plaintext",0,0],"v":2,"ct":"pboOo2xHIm15jQgX9/P1JW3Xu4x4WF+RwuYPhSpGkT3HtnmXxPNPL0750HrEeQ==","meta":{"expire":"1day"}}
Response:       {'url': '/privatebin/?fb0e3438db7a1059', 'deletetoken': '6f153102f875064793c78b43d879cb367a0b02f4e3b4f717e4bb3628ace661e9', 'status': 0, 'id': 'fb0e3438db7a1059'}

Paste uploaded!
PasteID:        fb0e3438db7a1059
Password:       BpGGeG29Hmn1VU7iASrmLGLcBx9Wvb2Rnv4dGpDZ2JiF
Delete token:   6f153102f875064793c78b43d879cb367a0b02f4e3b4f717e4bb3628ace661e9

Link:           https://<yourdomain>/privatebin/?fb0e3438db7a1059#BpGGeG29Hmn1VU7iASrmLGLcBx9Wvb2Rnv4dGpDZ2JiF
```

I think issue was because you not added trailing slash (`/`) in the end of link when tested. Like `"https://<yourdomain>/privatebin"`.
In the end we got forwarding reply instead applying data to PrivateBin instance which causes empty response.
Will add workaround.
