### ISSUE TITLE
Empty response if URL is subdirectory and without trailing slash

### ISSUE THREAD

**Issue by r4sas** [r4sas/PBinCLI#18]
I  have installed letsencrypt certificate and tested again. It produced the following response:
**ERROR: Unable parse response as json. Received (size = 0):**

_Originally posted by @muralikodali in https://github.com/r4sas/PBinCLI/issues/15#issuecomment-529216208_

**Comment by r4sas** [comment]
@muralikodali please check.

**Comment by muralikodali** [comment]
After adding forward slash (/) to the server url , pbincli worked without any problem.
Thanks for your help.
