### ISSUE TITLE
How is the current status?

### ISSUE THREAD

**Issue by rugk** [r4sas/PBinCLI#2]
Nice project, but is it working with PrivateBin 1.1?

Also, have you seen https://github.com/PrivateBin/PrivateBin-Cli?

**Comment by r4sas** [comment]
@rugk as I said at https://github.com/PrivateBin/PrivateBin/issues/242, current status is uncertain because I cant provide compressing used be current deflate module. Or we need setting or autodetect of non-compressed data.

**Comment by r4sas** [comment]
Updated some stuff, added no-compression service hosted by myself in inet/i2p.

**Comment by rugk** [comment]
If everything works, you can add it to https://github.com/PrivateBin/PrivateBin/wiki/Third-party-clients, if you want.

**Comment by r4sas** [comment]
fixed in #5
