### ISSUE TITLE
error with module 'Crypto.Cipher.AES'

### ISSUE THREAD

**Issue by muralikodali** [r4sas/PBinCLI#20]
pbincli giving following error.

Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.7.3/bin/pbincli", line 8, in <module>
    sys.exit(main())
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/cli.py", line 116, in main
    args.func(args, api_client, settings=CONFIG)
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/actions.py", line 44, in send
    expiration = args.expire)
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/format.py", line 229, in encrypt
    if self._version == 2: self._encryptV2()
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/format.py", line 261, in _encryptV2
    cipher = self.__initializeCipher(key, iv, adata)
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/format.py", line 121, in __initializeCipher
    cipher = AES.new(key, AES.MODE_GCM, nonce=iv, mac_len=CIPHER_TAG_BYTES)
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_GCM'

**Comment by r4sas** [comment]
Please give `pip show pycryptodome` output.

**Comment by muralikodali** [comment]
output is:

Name: pycryptodome
Version: 3.9.4
Summary: Cryptographic library for Python
Home-page: https://www.pycryptodome.org
Author: Helder Eijs
Author-email: helderijs@gmail.com
License: BSD, Public Domain, Apache
Location: /home/zenova/projects/pyenv/.pyenv/versions/3.7.3/lib/python3.7/site-packages
Requires: 
Required-by: streamlink, sjcl, pdfminer.six, PBinCLI

**Comment by r4sas** [comment]
Have you installed pycrypto (not 'dome')? If it installed it can override imports...

**Comment by r4sas** [comment]
Possible reason+solution: https://stackoverflow.com/a/48175912

**Comment by muralikodali** [comment]
removing pycryptodome and installing pycryptodomex as suggested by stackeroverflow link gives following errors :  

Traceback (most recent call last):
  File "/home/murali/.pyenv/versions/3.7.3/bin/pbincli", line 5, in <module>
    from pbincli.cli import main
  File "/home/murali/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/cli.py", line 4, in <module>
    import pbincli.actions
  File "/home/XXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/actions.py", line 1, in <module>
    from pbincli.format import Paste
  File "/home/XXXX/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pbincli/format.py", line 1, in <module>
    from Crypto.Random import get_random_bytes
ImportError: cannot import name 'get_random_bytes' from 'Crypto.Random' (unknown location)

**Comment by r4sas** [comment]
If you want use pycryptodomex, you need also rewrite imports in format.py from `Crypto` to `Cryptodome`. I'll add that in repo bit later...

**Comment by r4sas** [comment]
How do you think, is this will be enough?

```patch
--- a/pbincli/format.py
+++ b/pbincli/format.py
@@ -1,9 +1,23 @@
-from Crypto.Random import get_random_bytes
-from Crypto.Cipher import AES
 from base64 import b64encode, b64decode
 from pbincli.utils import PBinCLIError
 import zlib

+# Cryptography from pycryptodome
+from Crypto.Random import get_random_bytes
+
+# try import AES cipher and check if it has GCM mode (prevent usage of pycrypto)
+try:
+    from Crypto.Cipher import AES
+    if not hasattr(AES, 'MODE_GCM'):
+        print("[WARNING] AES GCM mode is not found in imported crypto module.\n[WARNING] That can happen if you have installed pycrypto.\n[WARNING] Trying import pycryptodomex...")
+        try:
+            from Cryptodome.Cipher import AES
+        except ImportError:
+            PBinCLIError("Unable import pycryptodomex. Please install it via pip by running:\n\tpip install pycryptodomex\n... or use separate python environment, or uninstall pycrypto:\n\tpip uninstall pycrypto")
+except ImportError:
+    PBinCLIError("Unable import pycryptodome")
+
+
```

Will look like
```
(venv) /usr/src/pbincli# pbincli
[WARNING] AES GCM mode is not found in imported crypto module.
[WARNING] That can happen if you have installed pycrypto.
[WARNING] Trying import pycryptodomex...
PBinCLI Error: Unable import pycryptodomex. Please install it via pip by running:
        pip install pycryptodomex
... or use separate python environment, or uninstall pycrypto:
        pip uninstall pycrypto
```

**Comment by r4sas** [comment]
added check in https://github.com/r4sas/PBinCLI/commit/19f130feb1e8e228a3511b57f5cb10862fed7632.
