### ISSUE TITLE
Tarball misses LICENSE and requirements.txt

### ISSUE THREAD

**Issue by nblock** [r4sas/PBinCLI#21]
While packaging pbincli for Arch Linux (https://aur.archlinux.org/packages/pbincli/), I noticed that the tarball misses the files LICENSE and requirements.txt.

**Comment by dedunumax** [comment]
This repository was a lifesaver, thanks a lot! Saved a lot of time!

**Comment by r4sas** [comment]
Fixed in 0.3.1.
