### ISSUE TITLE
Failed to decompress downloaded paste, part 2

### ISSUE THREAD

**Issue by foucist** [r4sas/PBinCLI#22]
Hello, I'm noticing possibly a very similar issue to #14 where I'm unable to properly get some pastes that I'm not the author of.  The only difference I notice is kdf_keysize being 128.  The vim.cx is version 1.3, and I compared against paste.biocrafting.net of the same version and the js files all matched up (except vim.cx doesn't have base64-1.7.js).

Example:  `
https://vim.cx/?23854101733f88cd#C9nHwV1PgScHGR3Ypo6CiUgmk5tZPjBusuH3yqF1Epy
`

gives me the error:
```
  File "/usr/local/lib/python3.7/site-packages/pbincli/format.py", line 186, in _decryptV2
    cipher_message = json_decode(self.__decompress(cipher.decrypt_and_verify(cipher_text, cipher_tag)).decode())
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/_mode_gcm.py", line 567, in decrypt_and_verify
    self.verify(received_mac_tag)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/_mode_gcm.py", line 508, in verify
    raise ValueError("MAC check failed")
ValueError: MAC check failed
```

However, if I clone it, the new link has a kdf_keysize of 256, and decompresses just fine.

I tried playing with the various values of the constants, mac_len value, and values that __deriveKey() uses, as well as the cipher_text_tag truncation, etc but can't seem to find the right combination to make it all work.  Any thoughts?

**Comment by r4sas** [comment]
You must change `CIPHER_TAG_BITS = 128` instead calculation and `CIPHER_BLOCK_BITS = 128`  and everything will work.

Will think how to do it better.
