### ISSUE TITLE
How to install virtualenv --python=python3 venv and . venv/bin/activate

### ISSUE THREAD

**Issue by ZerooCool** [r4sas/PBinCLI#25]
How to install, with debian ?

```
virtualenv --python=python3 venv
. venv/bin/activate
```

```
virtualenv --python=python3 venv
bash: virtualenv : commande introuvable
. venv/bin/activate
bash: venv/bin/activate: Aucun fichier ou dossier de ce type
```

**Comment by r4sas** [comment]
In that case you must use module inside Python:
```bash
pip3 install virtualenv
python3 -m virtualenv --python=python3 venv
. venv/bin/activate
```

**Comment by ZerooCool** [comment]
Ho yeah !
Work good !
Thank you !

In french :

https://wiki.visionduweb.fr/index.php?title=Exporter_un_fichier_texte_vers_un_service_en_ligne_de_type_pastebin#PBinCLI

But, i have this bug : 
#26

And, i don't how i can use the help : 

`pbincli -h send`

```
usage: pbincli [-h] {send,get,delete} ...

optional arguments:
  -h, --help         show this help message and exit

actions:
  {send,get,delete}  List of commands
```

Apart from this concern, this procedure seems much faster and lighter than the method I tested first, which required a long time of compilation with make / male install : 
https://wiki.visionduweb.fr/index.php?title=Exporter_un_fichier_texte_vers_un_service_en_ligne_de_type_pastebin#Privatebin-cli

**Comment by ZerooCool** [comment]
On the other hand, I don't know much about python and virtual environments.

My terminal now displays:
(venv) root@altcoins

How do I exit to find my terminal without the virtual environment?
use "exit" ?

How should you return to the virtual environment?
use : 
```
python3 -m virtualenv --python=python3 venv
. venv/bin/activate
```

It should not be too complicated, despite everything, it requires entering commands to be able to export a log file for example, and launching a virtual environment.
It will be necessary to simplify this to have less command to launch.
If need be, create an alias, to save time.

**Comment by r4sas** [comment]
Use `deactivate`.
RTFM: https://virtualenv.pypa.io/en/stable/user_guide.html#activators

**Comment by ZerooCool** [comment]
Ok for that, i have add that to my wiki and work well.

I am a little surprised, when I restart my VM, and, from the virtual environment, the pbincli package was no longer present.
I therefore suppose that the virtual environment destroys this during a restart, or when it is closed.

**Comment by r4sas** [comment]
Really dont know what you done...
You must initialize virtual environment only once, and then just activate it with:
 `. /path/to/venv/bin/activate`

**Comment by ZerooCool** [comment]
Easy, i learn, and, i create a real documentation, for install a cli for Privatebin.
Look my synthese here : https://github.com/PrivateBin/PrivateBin/issues/649

With that, i can export my log.file to my privatebin.
2.5 / 4 client tested.
2.5 / 4 documentation readable for a newby.

Thank you for your answer.
With that, I can make a better documentation more readable.

**Comment by ZerooCool** [comment]
Then if i desactive, and, shutdown the vm,
And, when i restart my VM, and active the env,
Is the package pbincli supposed to be installed ?

I have in any case noted that I must activate the environment as follows:
```
python3 -m virtualenv --python=python3 venv
. venv/bin/activate
```

At a minimum, install once:
`pip install pbincli`

I have to test again, because previously I had to install this package again.
Maybe now that I activate and deactivate correctly, the package will stay?

Then deactivate it as follows:
`deactivate`

**Comment by r4sas** [comment]
Adding `enhancement` as mark for updating docs.
