### ISSUE TITLE
Installation on Debian Buster #25 Ok but bug for send a file

### ISSUE THREAD

**Issue by ZerooCool** [r4sas/PBinCLI#26]
Send a file, example from README :
pbincli send -c "FILE LOG" -f FILE.log
pbincli send: error: argument -c/--compression: invalid choice: 'FILE LOG' (choose from 'zlib', 'none')

pbincli send -c "none" -f FILE.log
pbincli send -c 'none' -f FILE.log
pbincli send -c none -f FILE.log
Waiiitiiing .... and ..... nothing ......

pbincli send -f FILE.log
pbincli send -f /home/folder/FILE.log
Waiiitiiing .... and ..... nothing ......

Solved : 
cat FILE.log | pbincli send

**Comment by r4sas** [comment]
There is no bug. Read `pbincli send -h` output.

PS. I really don't know why argparse place `[-h]` before command.
Documentation in README need to be updated.

**Comment by ZerooCool** [comment]
You may have noticed, but, I wrote my comments along the way.

Here, I mainly mention that the compression command, -c none, followed by a file, -f file.log, does not work, and, runs in a vacuum.

I invite you to test, or, to tell me the correct method of use to use compression.
I just wanted to test the example offered, but, I can't.

On the other hand, I was able to export text, or, the file content, but, not using -c

For help, I was able to display it, as you told me.

Regarding the -c command, the issue remains open!
The control turns in a vacuum, without any action, without error message.

**Comment by r4sas** [comment]
Please provide info about:
* Server address
* Logfile weight

I'll test it myself.

Also, try use debug flag.

**Comment by ZerooCool** [comment]
I am using a Debian server.
But, in fact, in the options of my PrivateBin, I don't allow files.
I discover the tool.

I only notice one thing, that by default, with the default configuration, if I try to use the -c parameter, it does not work.

My privatebin:

https://privatebin.visionduweb.fr

WORK :
```
pbincli send --text "Hello!"
cat FILE.log | pbincli send
```

NOT WORK : 
```
pbincli send -c "FILE LOG" -f FILE.log
pbincli send: error: argument -c/--compression: invalid choice: 'FILE LOG' (choose from 'zlib', 'none')
```

NOT WORK : 
```
pbincli send -c "none" -f FILE.log
...waiting...
pbincli send -f FILE.log
...waiting...
pbincli send -f /home/folder/FILE.log
...waiting...
```

**Comment by r4sas** [comment]
Asking you for debug output (you can strip sensitive data) with `--debug` flag again.
And asking again about log weight. Is it's size 2MB, 20MB, 200MB, etc?

I dont understand what you want to achieve with `FILE LOG` value? Is that is comment or what?

Have you read `-h` output?
Have you tried   `-q, --notext` option? You must use it if you trying to send only file without text, see `-t, --text` description: `text in quotes. Ignored if used stdin. If not used, forcefully used stdin`

Are you trying send file content or file itself?

**Comment by ZerooCool** [comment]
Ok, just do it, there is a channel Discord for PrivateBin : 
https://discord.gg/a8Kf3ya

**Comment by ZerooCool** [comment]
But, i use your README :

```
o send file use --file or -f with filename. Example:
pbincli send -c "My document" -f info.pdf
```

And, never, i see other info :) 

Then, i note the option debug, and, i test that tomorrow.

Yes i have use the -h, then, the syntaxe is strange, and, your proposition work.
`pbincli send -h`

I don't have test that : 
`-q, --notext`

In my first test : 
pbincli send -c "FILE LOG" -f FILE.log
FILE LOG is a comment yes, the same for your, with "My document" in your README. No ?
My File.log contain text for test, less 20 ko.

>>I dont understand what you want to achieve with FILE LOG value?
The same for me ;) 
I test the command from your README, for learn, with privatebin.
Then, i don't know what i can do whith that.

**Comment by r4sas** [comment]
As I said earlier, documentation in README is too old and need to be updated.

In your case, you must use that command:
`pbincli send -t "FILE LOG" -f FILE.log`

**Comment by ZerooCool** [comment]
Ok for me ! Thank you for your answer.
Yes for that : 
` pbincli send -t "FILE LOG" -f FILE.log`

If you can up the README ;)

In french, that's my tutoriel : https://wiki.visionduweb.fr/index.php?title=Exporter_un_fichier_texte_vers_un_service_en_ligne_de_type_pastebin#PBinCLI

Ho, a other question, 
Who comes first, the egg, or the chicken? Sorry, it's late here.

PrivateBin-Python-Cli - Original : https://github.com/PrivateBin/PrivateBin-Python-Cli
PrivateBin-Python-Cli - Plus récent : https://github.com/r4sas/PBinCLI

Can you confirm, PrivateBin-Python-Cli is at the origin of PBinCLI?
Which one to consider as maintained to date?

**Comment by r4sas** [comment]
Initially was PBinCLI, which was forked to PrivateBin-Python-Cli by @elrido: https://github.com/r4sas/PBinCLI/pull/13#issuecomment-513897617...

Also see https://github.com/PrivateBin/PrivateBin/issues/188.

**Comment by r4sas** [comment]
Adding `enhancement` as mark for updating docs.

**Comment by ZerooCool** [comment]
Note that, for my part, I had not activated the authorization to send files to PrivateBin, and, I was able to discover this.
I have now set up file sharing on my PrivateBin instance.

Thank you for answering my questions.
