### ISSUE TITLE
Allow URL shortening via Shlink

### ISSUE THREAD

**Issue by tacerus** [r4sas/PBinCLI#28]
Hi,

whilst I can shorten PrivateBin URLs via a Shlink API string set in the PrivateBin config just fine when pasting text on my PrivateBin instance, the same sort of string does not seem to  be supported in PBinCLI.

`pbincli send: error: argument --short-api: invalid choice: 'shlink' (choose from 'tinyurl', 'clckru', 'isgd', 'vgd', 'cuttly', 'yourls')`

It would be nice if either support for Shlink was added, or if there was an option to just use universal strings, the same way they are supported in PrivateBin itself.

Cheers!

**Comment by r4sas** [comment]
Hello. That's good idea, maybe will add it soon.

**Comment by r4sas** [comment]
@tacerus please test using "custom" as `short-api` and by providing URL in `short-url` option. Example for Shlink is in commit description.

**Comment by tacerus** [comment]
Wow, thank you so much - I will try it later on!

**Comment by tacerus** [comment]
Works perfectly!

There was a super tiny bug with parsing the URL if specified in the configuration file, as it tried to split the second `=`. I'll attach a PR.

**Comment by r4sas** [comment]
Hm, interesting finding. Thank you!
