### ISSUE TITLE
Allow URL shortening preset in the config

### ISSUE THREAD

**Issue by tacerus** [r4sas/PBinCLI#29]
Hi,

it would be nice if one could pre-define a URL shortening service in the config, in order not having to specify the shortening options manually each time.

Cheers and Thanks for the otherwise awesome tool!

**Comment by r4sas** [comment]
Hello. Are you mean about `--short` option?
Otherwise here already options are present: https://github.com/r4sas/PBinCLI/blob/94023a986d87769a230250e1ce39c2c93427b6a9/pbincli/cli.py#L95-L105

**Comment by tacerus** [comment]
Hi, thank you! I checked the documentation but didn't see there were entries for the shortening service in the config!
