### ISSUE TITLE
fr add -v flag verbose --- for better user-friendliness.

### ISSUE THREAD

**Issue by tattwamasii2p** [r4sas/PBinCLI#32]
so that `pbincli -v` would print "uploading paste..." immediately after stdin eof received for better user-friendliness.

example:

```
root@desktop1:~# alias pastei2p="echo 'paste the text to stdin' && pbincli -v send -s http://paste.r4sas.i2p/ -x http://127.0.0.1:4444/"
root@desktop1:~# pastei2p
paste the text to stdin
usage: pbincli [-h] {send,get,delete} ...
pbincli: error: unrecognized arguments: -v
```

so

**Comment by r4sas** [comment]
`pbincli send -d`
About `sending paste` - will add soon.

**Comment by tattwamasii2p** [comment]
> `pbincli send -d`

AFAIR, I had some issues with that flag, needs retrying.

**Comment by tattwamasii2p** [comment]
And more common is to have a `-v` flag.

**Comment by r4sas** [comment]
А зачем? Там максимум что можно добавить в подробный вывод - это 2 сообщения о том что паста создается, паста отправляется.
