### ISSUE TITLE
Support onion addresses

### ISSUE THREAD

**Issue by q7nm** [r4sas/PBinCLI#33]
Add onion addresses support and for convenience convert onion to clearnet address in the command output (so people can open the link without tor). Config for example:
```
server=https://bin.snopyta.org
onion_server=http://5cs6g2gtee7lqkbvliotggauvwi7vtc6tmgw2li7jzmoyoeuvqwsldqd.onion
proxy=socks5://127.0.0.1:9050
```
```
$ pbincli send -t text
Paste uploaded!
PasteID:	xyz
Password:	xyz
Delete token:	xyz

Link:		https://bin.snopyta.org/xyz
Onion link:     http://5cs6g2gtee7lqkbvliotggauvwi7vtc6tmgw2li7jzmoyoeuvqwsldqd.onion/xyz
```

**Comment by r4sas** [comment]
I think that this is useless. Onion is not only one network, so we must add for every one? I2P, Yggdrasil, cjdns, etc, etc, etc...

**Comment by q7nm** [comment]
> I think that this is useless. Onion is not only one network, so we must add for every one? I2P, Yggdrasil, cjdns, etc, etc, etc...

Maybe it's better to limit ourselves to only onion and i2p then?

**Comment by r4sas** [comment]
Maybe better something like `mirror_domains` with comma-separated list, which will be used to print as mirrors for every parsed domain?

**Comment by r4sas** [comment]
Added feature usage: use flag `-L` or `--mirrors` with comma-separated list of URLs.
Example for config file:
```
mirrors = http://privatebin.ygg/,http://privatebin.i2p/
```

And output will look like:
```
Paste uploaded!
PasteID:        xxx
Password:       yyy
Delete token:   zzz

Link:           https://paste.i2pd.xyz/?xxx#yyy
Delete Link:    https://paste.i2pd.xyz/?pasteid=xxx&deletetoken=zzz

Mirrors:
                http://privatebin.ygg/?xxx#yyy
                http://privatebin.i2p/?xxx#yyy
```
