### ISSUE TITLE
Allow changing timer, BOR, open discussion, and more

### ISSUE THREAD

**Issue by hiddeninthesand** [r4sas/PBinCLI#36]
As far as I can tell, PBinCLI doesn't support these features and only goes with the default week timer with no bells and whistles. Allowing the timer to be changed, burn-on-read to be enabled, discussions and syntax changes, etc, would massively improve the usefulness of the program.

**Comment by hiddeninthesand** [comment]
Upon further inspection it seems that I'm stupid, though being able to change the defaults for these would be appreciated and still falls in with the tone of the issue.

**Comment by r4sas** [comment]
I hope that's what you mean, thank you for proposition.
