### ISSUE TITLE
`burn=true` in config ignored

### ISSUE THREAD

**Issue by xrat** [r4sas/PBinCLI#37]
I have installed v0.3.2 and my `pbincli.conf` reads
```
server=https://paste.i2pd.xyz/
expire=1day
burn=True
```
Yet, `pbincli send -t test` does not use the **burn after reading** option, whereas `pbincli send --burn -t test` works as expected.

**Comment by r4sas** [comment]
Because additional options support for config file was added after 0.3.2. Check it with 0.3.3.

**Comment by xrat** [comment]
Oh, sorry, I missed that detail. I used `pip` which got me 0.3.2.

**Comment by r4sas** [comment]
Uploaded 0.3.3 to pypi, please reinstall package
`python -m pip install --upgrade pbincli`

**Comment by xrat** [comment]
Thanks a lot. I upgraded but the problem persists. My setting "expire" is picked up, but "burn=true" is ignored.

Edit:
```
$ pip3 install --user --upgrade pbincli
(...)
Downloading PBinCLI-0.3.3-py3-none-any.whl (15 kB)
(...)
Successfully installed pbincli-0.3.3
```

**Comment by r4sas** [comment]
Ah, seems like [read_config](https://github.com/r4sas/PBinCLI/blob/d8f3c44371051e661c11b58f47d7a82b8d8eb7b0/pbincli/cli.py#L18) reads `True` as string, not boolean

**Comment by r4sas** [comment]
Tagged 0.3.4, please check it.

**Comment by xrat** [comment]
Thanks a lot. I tested it w/ `True`, `true`, `false`, no config option, and `-B`. All worked as expected.

I realized, though, that the CLI does not yet allow to reverse `burn=true` if set via the config. No issue for me right now, but I wanted to mention it just in case.

**Comment by r4sas** [comment]
Of course it won't, because the launch option cannot set an inverted flag. If I try to implement this, it will just add unnecessary complexity to the code.
