### ISSUE TITLE
Support for custom HTTP Headers on the `send` fuction

### ISSUE THREAD

**Issue by cwilson21** [r4sas/PBinCLI#41]
Currently this just allows for you to send something to a public system however having functionality to send this to a system that requires some type of authorization header would be nice. 

With the CLI it would be something like: 

server=https://someprivate.bin/
pbincli send -H '"Custom": "header"' -t "This is a test paste"

**Comment by r4sas** [comment]
Custom headers, not Basic-Auth like?

**Comment by cwilson21** [comment]
Like the ability to add a header for a bearer token for an instance behind Google IAP. 

`Authorization: Bearer $token`

As an example the instance I am using is a private instance of privatebin that is running in Google Cloud Run backed by GCS, and in front of it , it uses Googles Identity Aware Proxy for UI access, but you can use some gcloud api calls to create a Bearer token to pass with an `Authorization` header so it knows you are authenticated.

**Comment by r4sas** [comment]
Please try mentioned commit. Added options:

| Option | Default | Possible value |
|---------|---------|----------------|
| auth (--auth) | None | `basic`, `custom` |
| auth_user (--auth-user) | None | Basic authorization username |
| auth_pass (--auth-pass) | None | Basic authorization password |
| auth_custom (--auth-custom) | None | Custom authorization headers in JSON format, like `"{'Authorization': 'Bearer token'}"` |

I haven't tried changes, so, if there any issues, please tell about them.

**Comment by cwilson21** [comment]
I will pull this down and try it today.

**Comment by cwilson21** [comment]
So i am still looking at the code for this but this is the traceback. 

```Traceback (most recent call last):
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/curtis.wilson/.pyenv/versions/testpbin/bin/pbincli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/cli.py", line 184, in main
    args.func(args, api_client, settings=CONFIG)
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/actions.py", line 38, in send
    version = api_client.getVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/api.py", line 91, in getVersion
    proxies = self.proxy).json()
                          ^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by cwilson21** [comment]
The problem is in `api.py` line 89. 

`self.session` does not have the headers so it is not completing the request, the header for this needs to be added to `self.session.headers`

**Comment by cwilson21** [comment]
So right here, when you are calling getVersion in the actions file, self.session.headers is not getting the custom headers. 

https://github.com/r4sas/PBinCLI/blob/46149f868bcdeb7a8b1c6ad10362a34c28d7d91f/pbincli/actions.py#L37-L39

**Comment by r4sas** [comment]
Let's try this way:

```diff
--- a/pbincli/api.py
+++ b/pbincli/api.py
@@ -88,6 +88,7 @@ class PrivateBin:
     def getVersion(self):
         jsonldSchema = self.session.get(
             url = self.server + '?jsonld=paste',
+            headers = self.headers,
             proxies = self.proxy).json()
         return jsonldSchema['@context']['v']['@value'] \
             if ('@context' in jsonldSchema and

```

**Comment by r4sas** [comment]
`api_client` is created here, so it must have `self.headers`:
https://github.com/r4sas/PBinCLI/blob/46149f868bcdeb7a8b1c6ad10362a34c28d7d91f/pbincli/cli.py#L180

**Comment by r4sas** [comment]
> The problem is in `api.py` line 89.
> 
> `self.session` does not have the headers so it is not completing the request, the header for this needs to be added to `self.session.headers`

Good idea about using `headers` in session instead.

**Comment by r4sas** [comment]
Please try 8c5f934.

**Comment by cwilson21** [comment]
```Traceback (most recent call last):
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/curtis.wilson/.pyenv/versions/testpbin/bin/pbincli", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/cli.py", line 184, in main
    args.func(args, api_client, settings=CONFIG)
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/actions.py", line 38, in send
    version = api_client.getVersion()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/pbincli/api.py", line 86, in getVersion
    headers = self.headers).json()
                            ^^^^^^
  File "/Users/curtis.wilson/.pyenv/versions/3.8/envs/testpbin/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by cwilson21** [comment]
That is so strange so this works if I manually create things and do not use `pbincli` tool that is installed. 

```
In [16]: api_client=PrivateBin(settings)

In [17]: api_client.getVersion()
Out[17]: 2

**Comment by cwilson21** [comment]
```
{'server': 'https://privatebin.redacted.net',
 'no_insecure_warning': None,
 'no_check_certificate': None,
 'auth': 'custom',
 'auth_custom': '{"Authorization": "Bearer __REDACTEDHEAVILY__-_dn5-YmQAfAPg8kn--"}',
 'proxy': None}

**Comment by cwilson21** [comment]
I am trying to recall how I can execute `send` from `pbincli.actions` from the just a script/python command line. If I can do that then what I need can be achieved as I do not need to use the command line tool to do it, htat is just an added bonus.

**Comment by r4sas** [comment]
Can you send me your instance address and auth token for tests to `r4sas <dog> i2pd <dot> xyz`?

**Comment by cwilson21** [comment]
Unfortunately I cannot , that could land me in some deep trouble, aside from needing authorization from IAP you would also need to be connected to a VPN. I am done for the day, but I am going to look at this deeper tomorrow when I am fresh.

**Comment by r4sas** [comment]
Ah, okay. I'll set-up one more instance with restrictions to test myself.

**Comment by r4sas** [comment]
The current code works correctly with Basic Auth. Maybe the `Bearer` authorization requires something else?

**Comment by cwilson21** [comment]
Should require anything else. The code works, when called line by line in command line setting, it is just not working when called by the command line executeable, `pbincli send -s $server --auth-custom $JSON`

**Comment by r4sas** [comment]
Do you escape string passed in `$JSON`?

```
>pbincli send -s https://s2.i2pd.xyz/pbin/ --auth custom --auth-custom "{\"Authorization\": \"Bearer __REDACTEDHEAVILY__-_dn5-YmQAfAPg8kn--\"}" -t test!
Preparing paste…
{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer __REDACTEDHEAVILY__-_dn5-YmQAfAPg8kn--'}
Uploading paste…
{'User-Agent': 'python-requests/2.28.1', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Authorization': 'Bearer __REDACTEDHEAVILY__-_dn5-YmQAfAPg8kn--'}
PBinCLI Error: Unable parse response as json. Received (size = 172):
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Works as intended...

**Comment by r4sas** [comment]
Btw, why your PBin instance requires auth when `getVersion` is called? `send` needs only `POST`, isn't it? `jsonld` is not a thing that must be hidden ;)

**Comment by cwilson21** [comment]
So I added 2 print lines to the code at lines 84 & 85 of `api.py` which is in getVersion() right before it tries to make the request. Passing `--auth-custom` with my bearer token and it does not appear that the header is making it to the session or even to the headers. 

```Preparing paste…
Output of self.headers {'X-Requested-With': 'JSONHttpRequest'}
Output of self.session.headers {'User-Agent': 'python-requests/2.29.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive'}

**Comment by r4sas** [comment]
Did you updated installed package with `pip install -U .` in pbincli git dir after pulling changes?

**Comment by r4sas** [comment]
> Works as intended...

That output was gathered on 8c5f934 with adding of two lines to print session.headers:
```diff
diff --git a/pbincli/api.py b/pbincli/api.py
index 82f5197..326dc3d 100644
--- a/pbincli/api.py
+++ b/pbincli/api.py
@@ -41,6 +41,7 @@ class PrivateBin:
         self.session = _config_requests(settings, False)

     def post(self, request):
+        print(self.session.headers)
         result = self.session.post(
             url = self.server,
             headers = self.headers,
@@ -81,6 +82,7 @@ class PrivateBin:


     def getVersion(self):
+        print(self.session.headers)
         jsonldSchema = self.session.get(
             url = self.server + '?jsonld=paste',
             headers = self.headers).json()

```

**Comment by cwilson21** [comment]
@r4sas it is because our privatebin is meant for use in our company only , as those were the restrictions placed on us by our secops team that it only be accessible to the company internally.

**Comment by cwilson21** [comment]
This was done on https://github.com/r4sas/PBinCLI/commit/8c5f93487ac3da1d157090bdb784804f6d2471c4 after pulling all the latest changings and making sure I was on that commit, i did a `pip install -U .` when I added my changes to print the headers specifically for getVersion() i did a `pip install -U .`. When I run the following while using the 2 print statemetns in `getVersion()` printing headers i do not see the header I am passing ever making it into the session. You do not need a protected version of privatebin to test this, if you add lines where I did to print the value of each of thoseyou likely will see the same thing, when using the `--auth-custom` flag as the headers are not making it to getVersion for some reason. 

`pbincli send -s https://privatebin.redacted.net  --auth-custom "{'Authorization': 'Bearer ey`

**Comment by cwilson21** [comment]
Actually you can close this now. I am the idiot here. My pea brain did not see that there is a `--auth` along with `--auth-custom` this is what I get for working way after hours....

AKA - It works and I was just working when I shoudl ahve been asleep last night and imagining things.

**Comment by r4sas** [comment]
```nginx
map $http_authorization $pbin_reject {
    default "1";
    "Bearer mysuperbearer" "0";
}

...
    location ... {
        if ($pbin_reject) {
            return 401;
        }
...
```

```
>pbincli send -s https://s2.i2pd.xyz/pbin/ --auth custom --auth-custom "{\"Authorization\": \"Bearer mysuperbearer\"}" -t test!
Preparing paste…
Uploading paste…
Paste uploaded!
```

**Comment by r4sas** [comment]
> Actually you can close this now. I am the idiot here. My pea brain did not see that there is a `--auth` along with `--auth-custom` this is what I get for working way after hours....
> 
> AKA - It works and I was just working when I shoudl ahve been asleep last night and imagining things.

Ahaha ;)))

**Comment by cwilson21** [comment]
Sorry friend!

**Comment by r4sas** [comment]
Anyway, thank you for testing authorization. I'll add `try catch` block in `getVersion` to handle errors there too.
