### ISSUE TITLE
`distutils` is no longer usable from python 3.12 onwards

### ISSUE THREAD

**Issue by Saeden** [r4sas/PBinCLI#44]
In the `cli.py` script one of the imports is for `strtobool` from the distutils package. That package has been deprecated since python 3.10 and now, since 3.12, is no longer supported. I think the fix should be easy by adding a method that returns a bool, seeing as you already check if the string is either "true" or "false". 

Let me know if you want me to make a PR.

**Comment by r4sas** [comment]
Fixed in #47. Cudos to @brenard.
